### ISSUE TITLE
Question regarding the code

### ISSUE THREAD

**Issue by Larsonto** [amslabtech/dwa_planner#17]
Hi,

In motion function while finding the robot position x and y, it is always starting with 0 (State(0,0,0,current linear velocity, current angular velocity)) . So in this case x and y position will be from 0 to a maximum position of 2.0 or 3.0 . Then without knowing the current position  how do you find the distance for the far away obstacles? 

why - State(0,0,0,current linear velocity, current angular velocity)
why not - State(0,current_x,current_y,current linear velocity, current angular velocity)

**Comment by ToshikiNakamura0412** [comment]
This is because it is calculated with the base_link coordinate frame.
The local path planner is mostly used to avoid nearby obstacles that the robot can observe.
It works to some extent even if the robot's global pose cannot be accurately estimated because sensors can determine the location of obstacles relative to the robot.
